language: python
cache: pip

python:
  - "3.6"
  - "nightly"

install:
  - pip install mypy
  - pip install .

script:
  - mypy -m pqdict
  - python3 -m unittest discover -v -s test

notifications:
  email:
    on_failure: change
    on_success: never
